### ISSUE TITLE
Some methods support Collection other require plain array

### ISSUE THREAD

**Issue by jelhan** [cloudcreativity/json-api-testing#17]
I noticed that `assertFetchedMany` supports `Illuminate\Support\Collection` while `assertIncluded` does not.

https://github.com/cloudcreativity/json-api-testing/blob/28dc99483eb390f0016b72d85102e3e3cf9a64c5/src/Concerns/HasHttpAssertions.php#L485-L495

https://github.com/cloudcreativity/json-api-testing/blob/28dc99483eb390f0016b72d85102e3e3cf9a64c5/src/Concerns/HasHttpAssertions.php#L167-L174

This is not very intuitive. Not sure about the trade-offs but it would be great if all methods support any `iterable` and not only `array`.

**Comment by lindyhopchris** [comment]
Yeah good suggestion - when I first wrote the package you couldn't type-hint `iterable`; so this definitely needs to be reviewed now that PHP has moved on.
