### ISSUE TITLE
ability to set messages to assertions

### ISSUE THREAD

**Issue by riboflan** [cloudcreativity/json-api-testing#2]
Hi,

in first thank you for this handy package. It saves me lot of time.

This is only question about possibility to have this feature.

As in phpunit there you can do something like:
$this->assertEquals( 5, 6, "Multiplying 2 and 3 did not return 6");

Implementation of $message variable can be seen in PHPUnit\Framework\Assert class.

source: http://www.kreamer.org/phpunit-cookbook/1.0/assertions/display-useful-message-when-test-fails

I am just writing some integration tests that covers authorization testing. If the test fails then there is error in role settings in app. It can be handy to show info in console like:

$this->doRead($testingSubject)->assertStatus(403, 'In most cases this is wrong role settings in Bouncer');

This is only idea :).

Thanks.

**Comment by lindyhopchris** [comment]
Yes, thanks for the suggestion. There's definitely some assertions that could support messages, like the status one.

I'll take a look through and see where these can be added, but feel free to submit any PRs for the main ones you want to add in if you have time.
