### ISSUE TITLE
HttpAssert::assertStatusCode now expects $content to be a string but in case of file download it's a boolean

### ISSUE THREAD

**Issue by osteel** [cloudcreativity/json-api-testing#20]
Hi,

I'm currently upgrading a project to Laravel 9 and some tests are failing because of the newly introduced type-hints.

More specifically, calling `assertOk()` now fails for endpoints returning a file download:

```
TypeError: CloudCreativity\JsonApi\Testing\HttpAssert::assertStatusCode(): Argument #3 ($content) must be of type ?string, bool given, called in /var/www/vendor/cloudcreativity/json-api-testing/src/Concerns/HasHttpAssertions.php on line 103

/var/www/vendor/cloudcreativity/json-api-testing/src/HttpAssert.php:58
/var/www/vendor/cloudcreativity/json-api-testing/src/Concerns/HasHttpAssertions.php:103
/var/www/vendor/laravel-json-api/testing/src/TestResponse.php:195
/var/www/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:100
```

Possible solution would be to change [this line](https://github.com/cloudcreativity/json-api-testing/blob/develop/src/HttpAssert.php#L61) for:

```php
string|bool $content = null,
```

Cheers!

**Comment by lindyhopchris** [comment]
Hi! What's returning `false` for the response content? This method was never intended to support a boolean variable - it's expecting the string content of the response. So I think this is more something that should never have worked before is now not working because of a correct type-hint.

**Comment by osteel** [comment]
Just had a closer look – Symfony HttpFoundation's `Response@getContent()` can return `false` [indeed](https://github.com/symfony/http-foundation/blob/5.4/Response.php#L422). I guess it does so in case of a file download, somehow (as opposed to a regular response).

The request still is successful though, with a status code `200`. So I think I should still be able to call `->assertOk()` for such responses?

**Comment by lindyhopchris** [comment]
So I think this is more a problem with `laravel-json-api/testing` - it shouldn't be passing through `false` to this package, it should convert `false` to an empty string. I'll look into it and fix it via a patch release.

**Comment by osteel** [comment]
Nice! Thanks

**Comment by lindyhopchris** [comment]
@osteel I've tagged `v1.1.1` of the `laravel-json-api/testing` package. Can you give it a go and confirm it solves this problem?

**Comment by osteel** [comment]
That worked! Thanks
