### ISSUE TITLE
assertHasError will not match status codes

### ISSUE THREAD

**Issue by saernz** [cloudcreativity/json-api-testing#6]
It seems the `$response->assertHasError(409);` fails as it is trying to match a subset of the response document with "status" as an integer, but the JSON-API spec [requires the error "status" to be a string.](https://jsonapi.org/format/#errors)

Output of test:
Failed asserting that the array at [/errors] contains the subset:
```json
{
    "status": 409
}
```

within JSON API document:
```json
{
    "errors": [
        {
            "detail": "Blah blah blah",
            "status": "409",
            "title": "Some Conflict"
        }
    ]
}.
```

Currently the assertHasError method will only take $status as an int:
```php
public function assertHasError(int $status, array $error = [], bool $strict = true): self
```

**Comment by lindyhopchris** [comment]
Hi! Thanks for reporting - this definitely looks like a bug. I'll get it fixed.

**Comment by saernz** [comment]
Wow you're quick! Thanks man!

**Comment by lindyhopchris** [comment]
Ah no problem, was such a small fix it was easy to fix it quickly!
