### ISSUE TITLE
Add an assertion that no resources are included

### ISSUE THREAD

**Issue by jelhan** [cloudcreativity/json-api-testing#9]
Currently it's difficult to test that no resource are included. The only way I found so far is:

```php
$response->getDocument()->assertNull('/included');
```

That's not very ergonomic especially compared to `$response->assertIsIncluded()`, `$response->assertIncludes()` and `$response->assertIncluded()`.

I tried `$response->assertIncluded([])` but that results in an error that expected `[]` does not equal `null`. `$response->assertIncluded(null)` is not allowed by argument type.

**Comment by lindyhopchris** [comment]
Ah yes this is a good idea, adding something like `assertNoneIncluded()`. Any chance you're able to do a PR?

**Comment by jelhan** [comment]
I can try to do. Had a quick look into the code base and `CloudCreativity\JsonApi\Testing` already provides `Assert::assertNull()` and `Assert::assertListEmpty()`. Strictly speaking we would need an `Assert::assertListEmptyOrNull()` cause not having any resources included could mean not having an `included` member at all in the document or having an `included` member with an empty list. But do we need both cases in practice? Or do we have some kind of guarantee from `laravel-json-api` implementation that `included` member can't be an empty list?

**Comment by lindyhopchris** [comment]
So it should either not exist, or be an empty array. It should never be `null` as the spec says the `included` member must be an array, so `null` wouldn't be compliant with the spec.

**Comment by lindyhopchris** [comment]
This testing package is independent of `laravel-json-api` so shouldn't make any assumptions about what that package does.

As it can be either non-existent or an empty list, you'd probably need to add `Assert::assertListEmptyOrMissing()` , which will probably have to be done via a new constraint.

I can see how this might be complicated for you to do without any knowledge of the package. If you'd prefer me to do it then let me know, but I am quite pushed for work at the mo so it won't be immediately.

**Comment by jelhan** [comment]
@lindyhopchris Thanks a lot for implementing this one! :hugs: Haven't had any time to look into it. :cry:
